# Generated by Django 3.2.5 on 2023-04-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_alter_dataset_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='files',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/<function directory_path at 0x7fb348bacc10>/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.dataset')),
            ],
        ),
    ]
