# Generated by Django 4.2.3 on 2023-09-20 22:03

import analyze.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0004_file_scan_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="scan",
            field=models.ImageField(
                blank=True, null=True, upload_to=analyze.models.image_path
            ),
        ),
    ]
